acquia_lift.settings:
  type: config_object
  label: 'Acquia Lift settings'
  mapping:
    credential:
      type: config_object
      label: 'Credential'
      mapping:
        account_id:
          type: string
          label: 'Account ID'
        site_id:
          type: string
          label: 'Site ID'
        assets_url:
          type: uri
          label: 'Assets URL'
        decision_api_url:
          type: uri
          label: 'Decision API URL'
    identity:
      type: config_object
      label: 'Identity'
      mapping:
        capture_identity:
          type: boolean
          label: 'Capture identity'
        identity_parameter:
          type: string
          label: 'Identity parameter'
        identity_type_parameter:
          type: string
          label: 'Identity type parameter'
        default_identity_type:
          type: string
          label: 'Default identity type'
    field_mappings:
      type: config_object
      label: 'Field mappings'
      mapping:
        content_section:
          type: string
          label: 'Content section'
        content_keywords:
          type: string
          label: 'Content keywords'
        persona:
          type: string
          label: 'Persona'
    udf_person_mappings:
      type: sequence
      label: 'UDF Person mappings'
      sequence:
        type: config_object
        label: 'UDF Person mappings'
        mapping:
          id:
            type: string
            label: 'UDF Person field identifier.'
          value:
            type: string
            label: 'Item Value this is mapped to.'
          type:
            type: string
            label: 'Item Type this is mapped to.'
    udf_touch_mappings:
          type: sequence
          label: 'UDF Touch mappings'
          sequence:
            type: config_object
            label: 'UDF Touch mapping'
            mapping:
              id:
                type: string
                label: 'UDF Touch field identifier.'
              value:
                type: string
                label: 'Item Value this is mapped to.'
              type:
                type: string
                label: 'Item Type this is mapped to.'
    udf_event_mappings:
          type: sequence
          label: 'UDF Event mappings'
          sequence:
            type: config_object
            label: 'UDF Event mapping'
            mapping:
              id:
                type: string
                label: 'UDF Event field identifier.'
              value:
                type: string
                label: 'Item Value this is mapped to.'
              type:
                type: string
                label: 'Item Type this is mapped to.'
    visibility:
      type: config_object
      label: 'Visibility'
      mapping:
        path_patterns:
          type: string
          label: 'Path patterns'
    advanced:
      type: config_object
      label: 'Advanced'
      mapping:
        bootstrap_mode:
          type: string
          label: 'Bootstrap mode'
        content_replacement_mode:
          type: string
          label: 'Content replacement mode'
        cdf_version:
          type: integer
          label: 'Version of the CDF that is being used.'
    langcode:
      type: string
      label: 'Language code'
